### ISSUE TITLE
[BUG] Tap to focus and zoom does not trigger when archived

### ISSUE THREAD

**Issue by Andreasgejlm** [Mijick/CameraView#52]
I’m using your CameraView package for easy camera integration in my iOS app, and it’s been working great locally. However, I’ve encountered an issue when distributing the app via TestFlight.

Both UIPinchGestureRecognizer and UITapGestureRecognizer work perfectly in both debug and release configurations locally, but they fail to work when archived to a .ipa file. I’ve tried to set the build configuration of the archive to debug as well, but they do not trigger there as well 

Here’s the relevant code snippet from the package:
```
    fileprivate` class UICameraInputView: UIViewController {
        var cameraManager: CameraManager!

        override func viewDidLoad() {
            super.viewDidLoad()
            setupCameraManager()
            setupTapGesture()
            setupPinchGesture()
        }

        override func viewDidLayoutSubviews() {
            super.viewDidLayoutSubviews()
            cameraManager.fixCameraRotation()
        }
    }

    private extension UICameraInputView {
        func setupCameraManager() {
            cameraManager.setup(in: view)
        }

        func setupTapGesture() {
            let tapRecognizer = UITapGestureRecognizer(target: self, action: #selector(handleTapGesture))
            view.addGestureRecognizer(tapRecognizer)
        }

        func setupPinchGesture() {
            let pinchRecognizer = UIPinchGestureRecognizer(target: self, action: #selector(handlePinchGesture))
            view.addGestureRecognizer(pinchRecognizer)
        }

        @objc func handlePinchGesture(_ pinch: UIPinchGestureRecognizer) {
            if pinch.state == .changed {
                let desiredZoomFactor = cameraManager.attributes.zoomFactor + atan2(pinch.velocity, 33)
                changeZoomFactor(desiredZoomFactor)
            }
        }
    } 
```

I’ve ensured that the build settings for the archive configuration match those that worked locally, but the gesture recognizers do not trigger in the TestFlight and adhoc distribution.

Have you encountered this issue before, or do you have any suggestions on what might be going wrong?

Thanks in advance for your help!

**Comment by Andreasgejlm** [comment]
I tested it on a clean app, archived it, and installed the .ipa file to my phone locally, without going through TestFlight and the zoom and focus gestures are not triggering.

**Comment by FulcrumOne** [comment]
Hey @Andreasgejlm,

I suspected that this bug would occur because Apple has changed a few things related to concurrency in iOS 18. Unfortunately the same problems have appeared in our other libraries and I am currently working on [Popups](https://github.com/Mijick/Popups) that I plan to finish in the middle of November.

Next on my list is this library and I'm hoping that my experiences with [Popups](https://github.com/Mijick/Popups) will help me fix it significantly faster.

I apologise for the inconvenience, but I am currently the only person maintaining our six public and two private repositories +  I have several other responsibilities at the same time, therefore my efficiency is quite low, for which I sincerely apologise 😉

Have a nice day,
Tomasz

PS. You can join our [Discord](https://link.mijick.com/discord) to get the latest updates 😉

**Comment by Andreasgejlm** [comment]
Hi Tomasz,

No problem at all. I'm happy you're taking the time to maintain all of this. We are many happy customers.

Interesting with Apples changes to concurrency. I will have to read up on that 😊

**Comment by tiendq** [comment]
> Hi Tomasz,
> 
> No problem at all. I'm happy you're taking the time to maintain all of this. We are many happy customers.
> 
> Interesting with Apples changes to concurrency. I will have to read up on that 😊

/cc @FulcrumOne 

I face a new issue with focus. When I open camera the first time, focus works. But after I captured a photo, dismiss the camera view, and I open camera again (to capture another photo) then focus no longer work.

Tested on iPhone 11 and iOS 17.7

**Comment by FulcrumOne** [comment]
@tiendq, @Andreasgejlm,

Both problems should be resolved in the branch `patch-3.0.0`. Could you please confirm this? 

Thanks for your help,
Tomasz

**Comment by Andreasgejlm** [comment]
It's an iPhone 13 Mini and yes, I've only tested it on this device.

**Comment by FulcrumOne** [comment]
Thanks, I'll try to get back with something to test soon

**Comment by FulcrumOne** [comment]
@Andreasgejlm, sorry one more thing - could you try archiving [demo project](https://github.com/Mijick/CameraView-Demo) to eliminate the possibility that this is caused by part of your application code?

**Comment by Andreasgejlm** [comment]
No problem! I just did and the issue still persists.
Please, let me know if there's anything else you need.

**Comment by FulcrumOne** [comment]
@Andreasgejlm,

Could you please try archiving now? I have put the Discord webhooks in the code, which will allow me to check that the methods have actually been called

**Comment by FulcrumOne** [comment]
(but first please update to the head of that - `patch-3.0.0` branch)

**Comment by Andreasgejlm** [comment]
Done. I reinstalled the demo app with `patch-3.0.0` and tapped around.

**Comment by FulcrumOne** [comment]
Could you also use a pinch gesture?

**Comment by Andreasgejlm** [comment]
Sure. I just noticed something weird. On first open, the tap and pinch gestures are not registered. However, after a capture a photo and return to the capture screen, it suddenly works.

**Comment by FulcrumOne** [comment]
Yeah, I can see it
![CleanShot 2024-11-21 at 14 39 06](https://github.com/user-attachments/assets/bc5bb1d2-06ad-49f2-a2f0-1e88848ca7d5)

Looks to me like gestures are captured not in the main thread (for some reason)

**Comment by FulcrumOne** [comment]
Ok, sorry, but could you try updating the branch and archiving the app one more time? 😅

**Comment by Andreasgejlm** [comment]
I tapped and pinched a bit - no result. Captured an image, returned, and then it works.

**Comment by FulcrumOne** [comment]
@Andreasgejlm, ok, let's test another idea then - could you please repeat the action? And thank you very much for your help!

**Comment by FulcrumOne** [comment]
@Andreasgejlm, @tiendq,

Both issues have been fixed in the `patch-2.1.1` branch.

**Comment by tiendq** [comment]
> @Andreasgejlm, @tiendq,
> 
> Both issues have been fixed in the `patch-2.1.1` branch.

Sorry to not be able to reply soon, I just tested and it's fixed in `main` branch (v2.1.1). Thank you.
